name: "report"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "code-status"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: "Install Node Packages"
        run: npm install
      - name: "Check For Build Issues"
        run: npm run build
